# project-join-us


# compose syntax version.
version: "3.6"

# services declaration.
services:
  # MySQL
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=project-join-us
      - MYSQL_USER=project-join-us
      - MYSQL_PASSWORD=project-join-us
      - MYSQL_DATABASE=project-join-us
    ports:
      - target: 3306
        published: 3306
  # Redis
  redis:
    image: redis:5-alpine
    volumes:
      - redis-data:/data
    ports:
      - target: 6379
        published: 6379
  # Web Application
  web:
    image: ambientum/php:7.3-nginx
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    environment:
      - FRAMEWORK=laravel
      - XDEBUG_ENABLED=true
      - OPCACHE_MODE=normal
      - PHP_MEMORY_LIMIT=256M
    ports:
      - target: 8080
        published: 8080
      - target: 8083
        published: 8083
    links:
      - mysql
      - redis
      - mailhog
  # Laravel Queue Worker
  queue:
    image: ambientum/php:7.3
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    command:
      - php
      - artisan
      - queue:work
    environment:
      - FRAMEWORK=laravel
      - XDEBUG_ENABLED=false
      - OPCACHE_MODE=disabled
      - PHP_MEMORY_LIMIT=256M
    links:
      - mysql
      - redis
      - mailhog
  # MailHog
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - target: 1025
        published: 1025
      - target: 8025
        published: 8025

# volumes declaration.
volumes:
  # mysql-data
  mysql-data:
    driver: local
  # redis-data
  redis-data:
    driver: local
  # dot-config
  dot-config:
    driver: local
  # dot-cache
  dot-cache:
    driver: local
  # dot-local
  dot-local:
    driver: local
  # dot-composer
  dot-composer:
    driver: local
